# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('status', models.SmallIntegerField(choices=[(0, 'Released'), (1, 'Locked')], default=0)),
                ('last_action_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
