# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
